# Site settings

title: "folio"
tagline: swift development and more
version: 1.13.5 
copyright: © 2023 blueantcorp
url: www.blueantcorp.com
baseurl: blog.blueantcorp.com
paginate: 150
permalink: pretty
theme: jekyll-theme-minimal
analytics_id: ""

# About/contact
author: emile
name: emile
email: emile@blueantcorp.com
github: https://github.com/blueantcorp
linkedin: https://www.linkedin.com/in/emilep/

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate_path: "/blog/page:num/"

collections-permalink:
  projects:
    output: true
    permalink: /projects/:path/
  swiftui:
    output: true
    permalink: /swiftui/:path/

# Gems
plugins:
- jekyll-avatar
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-gist
