lsi: false
safe: true
incremental: false
gist:
  noscript: false

# Site settings
title: blueantcorp.com
description: descr about blueantcorp.com
email: info@blueantcorp.com


timezone: Europe/London

# Social
github: blueantcorp
twitter: blueantcorp
linkedin: blueantcorp

# U
baseurl: 
url:  https://www.blueantcorp.com


plugins_dir: _plugins

# Markdown
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: swift
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Pagination
paginate: 4
paginate_path: "/blog/:num/"
permalink: pretty
pretty: true

blueantcorp:

  author:
    name: emile
    email: emile@blueantcorp.com
    github: blueantcorp
    twitter: blueantcorp
    linkedin: emilep
    bio: bio.

  structure:
    - title: 'develop'
      category: 'development'
      description: 'mobile development'
      permalink: '/_development/index.html'
      published: true
      order: 2

    - title: 'build'
      category: 'toolchain'
      description: 'build and automation toolchain'
      published: true
      order: 3
    
    - title: 'plan'
      category: 'management'
      description: 'planning and management'
      published: true
      order: 1

    - title: 'teams'
      description: 'teams description'
    

# Collections
collections:
  development:
    output: true
    permalink: "/development/:title"

  toolchain:
    output: true
    permalink: "/toolchain/:title"

  management:
    output: true
    permalink: "/management/:title"

  teams:
    output: false
    permalink: "/teams/:title"

# Plugins
plugins:
  - jekyll-paginate