# Site settings
title: blueantcorp.com
description: descr about blueantcorp.com
email: info@blueantcorp.com

# Social
github: blueantcorp
twitter: blueantcorp
linkedin: blueantcorp

# Build settings
baseurl: 
url:  https://www.blueantcorp.com

markdown: kramdown
highlighter: rouge

author:
  name: emile
  email: emile@blueantcorp.com
  github: blueantcorp
  twitter: blueantcorp
  linkedin: emilep
  bio: bio.

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

navigation:

  - title: 'development'
    category: 'development'
    description: 'development description'
    permalink: '/development/'
    published: true
  
  - title: 'agile'
    description: 'agile description'
    published: true

  - title: 'teams'
    description: 'teams description'
    published: false
    

# Collections
collections:
  development:
    output: true
    permalink: /development/:title

  teams:
    output: true
    permalink: /teams/:title

  agile:
    output: true
    permalink: /agile/:title

exclude:
  - README.md
  - LICENSE

# Plugins
plugins:
  - jekyll-paginate