# Site settings
site:
  title: blueantcorp.com
  description: descr about blueantcorp.com
  email: info@blueantcorp.com

  # Social
  github: blueantcorp
  twitter: blueantcorp
  linkedin: blueantcorp

  # Build settings
  baseurl: /
  url:  https://www.blueantcorp.com
  markdown: kramdown
  highlighter: rouge

author:
  name: emile
  email: emile@blueantcorp.com
  github: blueantcorp
  twitter: blueantcorp
  linkedin: emilep
  bio: bio.

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

# Collections
collections:
  development:
    output: true
    permalink: /development/:path/
  teams:
    output: false
    permalink: /teams/:path/
  agile:
    output: true
    permalink: /agile/:path/

# Plugins
plugins:
  - jekyll-paginate