# Site settings
title: blueantcorp.com
email: info@blueantcorp.com
author: Emile
description: descr about blueantcorp.com
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://www.blueantcorp.com
twitter_username: blueantcorp
github_username:  blueantcorp

# Build settings
markdown: kramdown
highlighter: rouge

# Navigation
header_pages:
  - development.md
  # - teams.md
  # - agile.md
  - about.md

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  development:
    output: true
    permalink: /development/:path/
  teams:
    output: false
    permalink: /teams/:path/
  agile:
    output: true
    permalink: /agile/:path/

plugins:
  - jekyll-paginate