# Site settings
title: blueantcorp.com
description: descr about blueantcorp.com
email: info@blueantcorp.com

# Social
github: blueantcorp
twitter: blueantcorp
linkedin: blueantcorp

# Build settings
baseurl: 
url:  https://www.blueantcorp.com

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: swift
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: pretty
encoding: utf-8
timezone: Europe/London


author:
  name: emile
  email: emile@blueantcorp.com
  github: blueantcorp
  twitter: blueantcorp
  linkedin: emilep
  bio: bio.

# Pagination
paginate: 5
paginate_path: "/blog/:num/"

blueantcorp:
  $schema: "http://json-schema.org/draft-04/schema#"
  $id: "definitions/schema.json"
  structure:
    - title: 'develop'
      category: 'development'
      description: 'mobile development'
      permalink: '/development/'
      published: true
      order: 2

    - title: 'build'
      category: 'toolchain'
      description: 'build and automation toolchain'
      published: true
      order: 3
    
    - title: 'plan'
      category: 'management'
      description: 'planning and management'
      published: true
      order: 1

    - title: 'teams'
      description: 'teams description'
      order: 1
    

# Collections
collections:
  development:
    output: true
    permalink: "/development/:title"

  toolchain:
    output: true
    permalink: "/toolchain/:title"

  management:
    output: true
    permalink: "/management/:title"

  teams:
    output: false
    permalink: "/teams/:title"

# Plugins
plugins:
  - jekyll-paginate