# Site settings

title: *folio
tagline: swift development and more
version: 1.6.0 
copyright: \&#169; 2019 blueantcorp
url:  www.blueantcorp.com
baseurl: ""
paginate: 15
permalink: pretty
theme: jekyll-theme-minimal
analytics_id: ""

# About/contact

author:
name: emile
url: https://www.blueantcorp.com
email: emile@blueantcorp.com
github: https://github.com/blueantcorp

# Build settings

markdown: kramdown
highlighter: rouge

# Pagination

paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/

# Gems

plugins:
- jekyll-avatar
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
- jekyll-gist
